// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vryqshvyvguplgxhgrld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyeXFzaHZ5dmd1cGxneGhncmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTE0ODksImV4cCI6MjA3NDEyNzQ4OX0.Nysc-zmFgHtLmLAyeg90QHJjpcapxhMG4I456nYOi6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});